apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-xzzz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-xzzz
    app.kubernetes.io/part-of: integ-app-luuw
  name: hacbs-test-project-xzzz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-xzzz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-xzzz
    spec:
      containers:
      - image: quay.io/rycole-appstudio/integration1-tuvv-tenant/integ-app-luuw/hacbs-test-project-xzzz@sha256:533dd423c874cc6278132b65ee2f316d334e5b27cd5b3a240718699968946b9c
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
